// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTdVykRLSfJSU8NhipKCkrAGM63B6zVlc',
    appId: '1:818594929188:web:26ae961c6e4f6d9dff56b1',
    messagingSenderId: '818594929188',
    projectId: 'myportfolio-ab6cc',
    authDomain: 'myportfolio-ab6cc.firebaseapp.com',
    storageBucket: 'myportfolio-ab6cc.firebasestorage.app',
    measurementId: 'G-9SJ8KBFC60',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSWteWflWXttzBkNlA5ZDbvqV4MVsmXrU',
    appId: '1:818594929188:android:89db8dede5939ad3ff56b1',
    messagingSenderId: '818594929188',
    projectId: 'myportfolio-ab6cc',
    storageBucket: 'myportfolio-ab6cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw8F7u3wZvvkXruMrlO3E9nhimMLj2qKM',
    appId: '1:818594929188:ios:1b7fb4a5e221083cff56b1',
    messagingSenderId: '818594929188',
    projectId: 'myportfolio-ab6cc',
    storageBucket: 'myportfolio-ab6cc.firebasestorage.app',
    iosBundleId: 'com.example.webPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw8F7u3wZvvkXruMrlO3E9nhimMLj2qKM',
    appId: '1:818594929188:ios:1b7fb4a5e221083cff56b1',
    messagingSenderId: '818594929188',
    projectId: 'myportfolio-ab6cc',
    storageBucket: 'myportfolio-ab6cc.firebasestorage.app',
    iosBundleId: 'com.example.webPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTdVykRLSfJSU8NhipKCkrAGM63B6zVlc',
    appId: '1:818594929188:web:32f97fe27af40693ff56b1',
    messagingSenderId: '818594929188',
    projectId: 'myportfolio-ab6cc',
    authDomain: 'myportfolio-ab6cc.firebaseapp.com',
    storageBucket: 'myportfolio-ab6cc.firebasestorage.app',
    measurementId: 'G-0MT1YDSSLX',
  );
}
